### ISSUE TITLE
google analytics should take multiple IDs

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1340]
- [x] default should always be sent (unless configured off)
- [x] if a user wants to configure additional ids, they can do that

**Comment by nathandunn** [comment]
Closed by #1341

**Comment by childers** [comment]
I am not sure this is working properly. I've tried adding multiple values into the array, and it looks as though the tags are each being loaded twice.  Also everything but the first tag loaded shows an error when checking it via the Google Tag Assistant plugin for chrome.

I've been looking but have not yet found where the google analytics script is getting called twice.

**Comment by nathandunn** [comment]
@childers  Looking into this now.  I am getting this called:

https://www.google-analytics.com/collect?v=1&_v=j80&a=1694993923&t=pageview&_s=1&dl=http%3A%2F%2Fdemo.genomearchitect.org%2FApollo2%2Fannotator%2Findex&ul=en-us&de=UTF-8&dt=Annotator&sd=24-bit&sr=2560x1440&vp=805x1189&je=0&_u=AACAAEAB~&jid=&gjid=&cid=1909796929.1574372267&tid=UA-62921593-1&_gid=1558597717.1581350188&z=1279716293

These are called from the html landing pages:

https://github.com/GMOD/Apollo/blob/develop/grails-app/views/google_analytics.gsp#L8 

e.g., 

        google_analytics = ["UA-1234556-1","UA-62921593-1"]


Looks like you have that configured this way then? 

https://genomearchitect.readthedocs.io/en/latest/Configure.html#phone-home

I tried the same thing, and the loop gets run, but it definitely only uses the first ID only and it definitely sends it twice. 

I'll take a look as you should be able to do this . . but probably bad JS code on my part.

**Comment by nathandunn** [comment]
@childers  this should be fixed now (on develop) . . I tested it and it will send out data to both GA servers.

**Comment by childers** [comment]
I'm not getting errors anymore, but the tags are still getting loaded twice.

**Comment by childers** [comment]
logging in as a not-admin user seems to be ok. is there an element in the admin interface that is calling the analytics script a second time?

**Comment by nathandunn** [comment]
Should be better now 

Nathan
