### ISSUE TITLE
unable to add organism from script without pre-existing web-services

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1388]
When using the "add_organism.groovy" script, we for some reason still require an organism when the token is "ignore". 

Current workaround is to add:

        client_token : 'ignore',
        organism: 'some-existing-organism',

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/add_organism.groovy#L62

Longer-term solution.  

    - [ ] every webservice should add the client_token: 'ignore'
    - [ ] remove the condition of having an organism if the client_token is ignore? 

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/PermissionService.groovy#L613

@deepakunni3  You have any thoughts on this? 

FYI, reported by @childers

**Comment by deepakunni3** [comment]
Yes, it would make sense to remove the requirement for organism for operations that are organism agnostic.

**Comment by nathandunn** [comment]
- [ ] every webservice should add the client_token: 'ignore'
- [ ] remove the condition of having an organism if the client_token is ignore

- [ ] add functional tests for existing useful scripts

**Comment by nathandunn** [comment]
Confirmed that the REST API was correct (ie., it didn't have anything that wasn't needed / there).   Most of the scripts were correct, but for this bug.

**Comment by nathandunn** [comment]
FYI @erasche  You may want to pull from the master, this is fixed.   This small bug in 2.0.5 may break some of your web service scripts.

**Comment by erasche** [comment]
Thanks @nathandunn

**Comment by childers** [comment]
This looks like is still an issue in the current commit. 
I am trying to stand up a new database and am running into this issue again when trying to batch load my organisms via web services.

I was able to create the admin account, but after logging in it just hangs, so I cannot make a temporary organism that way.

 The error is:
```shell
{"error":"problem saving organism: java.lang.NullPointerException: Cannot invoke method first() on null object"}
HTTP/1.1 200 OK
Server: nginx/1.12.0
Date: Mon, 22 May 2017 19:43:50 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=2EB4AB8FEFA23018A47FBBE7D17F8B45; Path=/apollo/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/apollo; Max-Age=0; Expires=Sun, 21-May-2017 19:43:50 GMT
Front-End-Https: on

{"error":"problem saving organism: java.lang.NullPointerException: Cannot invoke method first() on null object"}HTTP/1.1 200 OK
Server: nginx/1.12.0
Date: Mon, 22 May 2017 19:43:50 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=8BBD8B70CCD12F30AE37915401A46DF3; Path=/apollo/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/apollo; Max-Age=0; Expires=Sun, 21-May-2017 19:43:50 GMT
Front-End-Https: on

{"error":"problem saving organism: java.lang.NullPointerException: Cannot invoke method first() on null object"}
```
The load command looks like:
```shell
curl -i -X POST -H "Content-Type: application/json" -d '{"username": "admin", "password": "hunter2", "commonName": "Big bug", "genus": "Big", "species": "bug", "directory": "/path/bigbug/data", "blatdb": "/path/genomic_RefSeqIDs.fna.2bi", "publicMode": "true", "client_token": "ignore"}' https://stage.server/apollo/organism/addOrganism
curl -i -X POST -H "Content-Type: application/json" -d '{"username": "admin", "password": "hunter2", "commonName": "Little bug", "genus": "Little", "species": "bug", "directory": "/path/littlebug/data", "blatdb": "/path/scaffolds.50.fa.2bi", "publicMode": "true", "client_token": "ignore"}' https://stage.server/apollo/organism/addOrganism
```
