### ISSUE TITLE
Unable to create user annotations on kubernetes/openshift platform

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [GMOD/Apollo#2373]
Hi,

I am using the quay.io/gmod/apollo:2.4.1 container image. While running the container locally with docker (on my linux computer) I can create user annotations perfectly fine and everything else works as expected. However, when using the container instance that is deployed on an openshift container platform, I am unable to create user annotations.

To further clarify, this is the expected behaviour
![expected_bahaviour](https://user-images.githubusercontent.com/7196110/74013647-43818700-498d-11ea-817f-9e0790583cdf.gif)

This is what happens on the container platform (which is nothing)
![what_happens_openshift](https://user-images.githubusercontent.com/7196110/74013650-441a1d80-498d-11ea-9641-b0af659cb26d.gif)

I'm puzzled on what is causing this issue, I wasn't able to find anything directly related in the logs (but quite likely I am just bad at reading them). Here are the logs of today: [2020-02-07_apollo_logs.txt](https://github.com/GMOD/Apollo/files/4169753/2020-02-07_apollo_logs.txt)

**Comment by nathandunn** [comment]
Hmm .  . . I'm seeing this error:

```
2020-02-07 08:11:12,108 [http-nio-8080-exec-6] ERROR errors.GrailsExceptionResolver  - IOException occurred when processing request: [GET] /597933606255001253860555172/jbrowse/dist/0.bundle.js
Broken pipe. Stacktrace follows:
java.io.IOException: Broken pipe
	at org.bbop.apollo.JbrowseController.passthrough(JbrowseController.groovy:615)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

But, what do you see in the javascript console and the javascript network tab?

For the network tab, you have to have that open ahead of time and you'll either see results when you do an add in the XHR tab, or in the WS frames view.

**Comment by Jorisvansteenbrugge** [comment]
Thank you for looking into it!

What is the best way to show these console/networks logs to you? (e.g. exporting them to a text file, screenshot, etc.)

**Comment by nathandunn** [comment]
Probably both ;) 

If you can open up any errors that is helpful.  I can usually make sense of them between the two.  Usually I just click, drag, and copy the relevant sections.

**Comment by Jorisvansteenbrugge** [comment]
Alright so this is the screenshot of the [Network tab](https://user-images.githubusercontent.com/7196110/74310426-7e106880-4d6d-11ea-9790-8f41a1f7cd82.png) I sorted on status so that might cause errors are on the bottom.

The console log screenshot is [here](https://user-images.githubusercontent.com/7196110/74310884-7b624300-4d6e-11ea-9137-fcf1d8d75f7e.png). If I expand everything it doesn't fit on the screenshot, so the full log is here: [apollo-1581490833789.log](https://github.com/GMOD/Apollo/files/4190299/apollo-1581490833789.log)

**Comment by nathandunn** [comment]
@Jorisvansteenbrugge   Thanks.   That's what I needed to see. 

Short answer is that I think I fixed this on the development branch https://github.com/GMOD/Apollo/commit/0b6d0f6f91de995f4d3d3798f13f82772f86b6ea

The easiest thing might be to update to development (https://github.com/GMOD/Apollo/archive/develop.zip) which should be pretty stable.  However, if you want to patch, that is fine as well.   Whenever 2.6.0 is release (probably next month) it will also be in there.

**Comment by Jorisvansteenbrugge** [comment]
Thank you very much for fixing it! I tried to build a docker image based on the develop zip archive, but that doesn't compile. From what I could find: the problem is the apt-get install command that attempts to install openjdk-8-jdk, which is not available in the default debian 10 repository.
In that case I might be better of waiting for the official 2.6.0 release, do you agree?

**Comment by nathandunn** [comment]
I don't think the fix is in 2.6.0.     It looks like the build had only recently failed due to the openjdk error: https://quay.io/repository/gmod/apollo?tab=builds

I'll try to get that fixed today as there are many folks that rely on that image.

**Comment by nathandunn** [comment]
I hopefully fixed the build on latest.   Timestamp should be 12.10 PT roughly. 

https://quay.io/repository/gmod/apollo?tab=builds
https://hub.docker.com/r/gmod/apollo/builds

Please let me know if this fixes it and thanks for reporting.

**Comment by Jorisvansteenbrugge** [comment]
Running the image with example data works, I do however have an issue when trying to import the postgresql database. 
From the logs: "﻿Starting PostgreSQL 11 database server: mainError: /var/lib/postgresql/11/main is not accessible or does not exist ... failed!" 
Then this line just keeps repeating: "/var/run/postgresql:5432 - no response"

I know that the database files are fine, because when I roll back to 2.4.1, it works. Not sure if it is a separate issue, but this prevents me from using the updated image.

[apollocontainer-20.log](https://github.com/GMOD/Apollo/files/4203550/apollocontainer-20.log)

**Comment by nathandunn** [comment]
What flags are you to run the docker container?

The default in the container database is Postgres 9.6, so I’m wondering how its able to connect to postgresql 11:


% docker run -it -p 8080:8080 gmod/apollo:latest                           
[ ok ] Starting PostgreSQL 9.6 database server: main.
WEBAPOLLO_HOST_FLAG: 
CHADO_HOST_FLAG: 
Waiting for DB
/var/run/postgresql:5432 - accepting connections
Postgres is up, configuring database
psql: FATAL:  Peer authentication failed for user "apollo"
Apollo database not found, creating...
CREATE ROLE
GRANT
Not using chado!
APOLLO PATH 
FIXED_CTX PATH 
WAR FILE /usr/local/tomcat/webapps/.war
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
14-Feb-2020 17:17:39.472 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.30
14-Feb-2020 17:17:39.481 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 7 2019 16:42:04 UTC
14-Feb-2020 17:17:39.481 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.30.0
14-Feb-2020 17:17:39.481 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
14-Feb-2020 17:17:39.482 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.9.184-linuxkit


Nathan

**Comment by Jorisvansteenbrugge** [comment]
I'm leaving everything at default except for the admin password variable.
In my previous post I showed the log of the container running on openshift. When I pull the latest image from gmod/apollo:latest on my pc locally (using docker) It also defaults to PostgreSQL 11:

docker run -it -p 8888:8080 gmod/apollo:latest
bash: /usr/lib/postgresql/9.6/bin/initdb: No such file or directory
[ ok ] Starting PostgreSQL 11 database server: main.
WEBAPOLLO_HOST_FLAG: 
CHADO_HOST_FLAG: 
Waiting for DB
/var/run/postgresql:5432 - accepting connections
Postgres is up, configuring database
psql: FATAL:  Peer authentication failed for user "apollo"
Apollo database not found, creating...
CREATE ROLE
GRANT
Not using chado!
APOLLO PATH 
FIXED_CTX PATH 
WAR FILE /usr/local/tomcat/webapps/.war
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar

**Comment by nathandunn** [comment]
Its possible there is a bad / corrupted image in there?

I pruned my docker and it started right up, though its odd yours doesn’t seem to be loading the correct host. 



------

docker system prune
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Containers:
e7e27ad736ecb8a7e4653929786d2ff76d720f78f979f44f30aefa3ef2db98d8

Total reclaimed space: 452MB
nathandunn:TEMP% docker run -it -p 8888:8080 gmod/apollo:latest



docker run -it -p 8888:8080 gmod/apollo:latest

[ ok ] Starting PostgreSQL 9.6 database server: main.
WEBAPOLLO_HOST_FLAG: 
CHADO_HOST_FLAG: 
Waiting for DB
/var/run/postgresql:5432 - accepting connections
Postgres is up, configuring database
psql: FATAL:  Peer authentication failed for user "apollo"
Apollo database not found, creating...
CREATE ROLE
GRANT
Not using chado!
APOLLO PATH 
FIXED_CTX PATH 
WAR FILE /usr/local/tomcat/webapps/.war
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
17-Feb-2020 16:03:21.172 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.30
17-Feb-2020 16:03:21.182 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 7 2019 16:42:04 UTC
17-Feb-2020 16:03:21.183 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.30.0
17-Feb-2020 16:03:21.183 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
17-Feb-2020 16:03:21.184 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.19.76-linuxkit
17-Feb-2020 16:03:21.185 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
17-Feb-2020 16:03:21.185 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
17-Feb-2020 16:03:21.185 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_232-b09
17-Feb-2020 16:03:21.186 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
17-Feb-2020 16:03:21.186 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
17-Feb-2020 16:03:21.187 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
17-Feb-2020 16:03:21.199 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
17-Feb-2020 16:03:21.200 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
17-Feb-2020 16:03:21.200 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
17-Feb-2020 16:03:21.200 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
17-Feb-2020 16:03:21.201 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
17-Feb-2020 16:03:21.202 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
17-Feb-2020 16:03:21.202 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
17-Feb-2020 16:03:21.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
17-Feb-2020 16:03:21.203 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
17-Feb-2020 16:03:21.204 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.23] using APR version [1.5.2].
17-Feb-2020 16:03:21.205 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
17-Feb-2020 16:03:21.206 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
17-Feb-2020 16:03:21.216 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0l  10 Sep 2019]
17-Feb-2020 16:03:21.866 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
17-Feb-2020 16:03:21.932 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
17-Feb-2020 16:03:21.939 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1,348] milliseconds
17-Feb-2020 16:03:22.010 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
17-Feb-2020 16:03:22.011 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.30]
17-Feb-2020 16:03:22.053 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/.war]
17-Feb-2020 16:03:22.070 WARNING [main] org.apache.catalina.core.StandardContext.setPath A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
17-Feb-2020 16:03:32.168 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
WEBAPOLLO environment
WEBAPOLLO_OVERLAPPER_CLASS 
APOLLO_ADMIN_LAST_NAME 
WEBAPOLLO_START_POSTGRES true
WEBAPOLLO_COMMON_DATA 
WEBAPOLLO_USER_PASSWORD_AUTH 
WEBAPOLLO_GFF3_SOURCE 
WEBAPOLLO_GOOGLE_ANALYTICS_ID 
WEBAPOLLO_MINIMUM_INTRON_SIZE 
WEBAPOLLO_FEATURE_HAS_DBXREFS 
WEBAPOLLO_HISTORY_SIZE 
WEBAPOLLO_SPLICE_DONOR_SITES 
CHADO_DB_HOST 127.0.0.1
WEBAPOLLO_FEATURE_HAS_STATUS 
WEBAPOLLO_DB_HOST 127.0.0.1
CHADO_DB_PASSWORD apollo
WEBAPOLLO_FEATURE_HAS_GO 
WEBAPOLLO_FEATURE_HAS_PUBMED 
WEBAPOLLO_DB_PASSWORD apollo
WEBAPOLLO_FEATURE_HAS_ATTRS 
WEBAPOLLO_DB_NAME apollo
WEBAPOLLO_TRANSLATION_TABLE 
WEBAPOLLO_USE_CHADO 
WEBAPOLLO_SPLICE_ACCEPTOR_SITES 
WEBAPOLLO_REMOTE_USER_AUTH 
WEBAPOLLO_CDS_FOR_NEW_TRANSCRIPTS 
WEBAPOLLO_FEATURE_HAS_COMMENTS 
CHADO_DB_NAME chado
WEBAPOLLO_DB_USERNAME apollo
CHADO_DB_USERNAME apollo
APOLLO_ADMIN_FIRST_NAME 
APOLLO_ADMIN_EMAIL 
APOLLO_ADMIN_PASSWORD

**Comment by Jorisvansteenbrugge** [comment]
I pruned all docker images/containers and ran `docker pull gmod/apollo:latest`. I then used the same command as before `docker run -it -p 8888:8080 gmod/apollo:latest`, giving the same output: 

```
bash: /usr/lib/postgresql/9.6/bin/initdb: No such file or directory
[ ok ] Starting PostgreSQL 11 database server: main.
WEBAPOLLO_HOST_FLAG: 
CHADO_HOST_FLAG: 
Waiting for DB
/var/run/postgresql:5432 - accepting connections
Postgres is up, configuring database
psql: FATAL:  Peer authentication failed for user "apollo"
Apollo database not found, creating...
CREATE ROLE
GRANT
Not using chado!
APOLLO PATH 
FIXED_CTX PATH 
WAR FILE /usr/local/tomcat/webapps/.war
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/openjdk-8
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
```

**Comment by nathandunn** [comment]
Thanks.  I'm seeing the same thing now.   I didn't realize that it was using the same sticky tag for latest.   I'll get that fixed soon.

**Comment by nathandunn** [comment]
It looks like the base image changed, which is not cool.  I was running into the local and remote environment conflicting, but was able to bring them in sync here:

    docker pull tomcat:9-jdk8    

FYI @hexylena  / @abretaud / @luke-c-sargent 

Longer term, we should use an LTS base linux image.

**Comment by nathandunn** [comment]
@Jorisvansteenbrugge  This should be fixed momentarily on docker hub.  It might build a bit faster on quay https://quay.io/repository/gmod/apollo?tab=builds

    docker run -it -p 8888:8080 quay.io/gmod/apollo:latest

Otherwise it should be built in a couple of hours on docker hub.

Thanks again for reporting and sticking with it.

**Comment by Jorisvansteenbrugge** [comment]
I will test this soon on our system and I will keep you updated!

**Comment by Jorisvansteenbrugge** [comment]
Alright, so I tried the new image, this line is the first of the log file:
> Starting PostgreSQL 11 database server: mainRemoved stale pid file. Error: /usr/lib/postgresql/11/bin/pg_ctl /usr/lib/postgresql/11/bin/pg_ctl start -D /var/lib/postgresql/11/main -l /var/log/postgresql/postgresql-11-main.log -s -o -c config_file="/etc/postgresql/11/main/postgresql.conf" exited with status 1: 2020-02-19 11:16:54.575 UTC [26] FATAL: database files are incompatible with server 2020-02-19 11:16:54.575 UTC [26] DETAIL: The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 11.7 (Debian 11.7-0+deb10u1). pg_ctl: could not start server Examine the log output. ... failed!

Would you recommend to dump the 9.6 database and import it with postgresql 11, as just passing the database on does not seem to work?

**Comment by nathandunn** [comment]
> Would you recommend to dump the 9.6 database and import it with postgresql 11, as just passing the database on does not seem to work?

Yes.   I'll also try to update the image to do this, as other folks will no doubt run into this. 

You might also see if `pg_upgrade` might work, but its possible its too much of an update.

**Comment by nathandunn** [comment]
@Jorisvansteenbrugge  I'm going to try and fix the image so it doesn't require postgresql11 here: https://github.com/GMOD/Apollo/issues/2381

**Comment by nathandunn** [comment]
@Jorisvansteenbrugge  I have fixed this so in #2382 so will be PostgreSQL 9.6 in `latest` whenever it is rebuilt on docker hub.  Its usually a bit faster on quay if you'd rather try it there:

https://quay.io/repository/gmod/apollo?tab=builds

**Comment by Jorisvansteenbrugge** [comment]
@nathandunn I managed to get the instance running, thank you for all your work. I am however still unable to create user annotations (the exact same things happens as in the gif in my first post). Do you have any idea what is going on?

**Comment by Jorisvansteenbrugge** [comment]
I tried it with the latest develop image on quay:

Version: 2.6.0-SNAPSHOT
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.8.0_242
Servlet Container Version: Apache Tomcat/9.0.16 (Ubuntu)

**Comment by nathandunn** [comment]
Hey @Jorisvansteenbrugge  glad we were able to make a little progress.   I tried loading it up via openshift myself . . . a nice yet highly complicated platform.     I ran the container without any options using the quay.io/gmod/apollo:latest build . . . I don't really know what options to use here.  I actually had the same database problems you had (and no directories, and probably not port fofrwarded etc.), but that is beside the case.

Anyway, if you want to send me the same suite of logs you had from before, that would be helpful. 

Are you trying to do a proxy through nginx or just straight through tomcat, exposing port 8080 as 80, or are you using https?

**Comment by Jorisvansteenbrugge** [comment]
"a nice yet highly complicated platform" - I couldn't agree more haha. In the past I just had an instance running on a pc here, but the IT department of my university doesn't allow that anymore (which I understand, but it was a lot less complicated).

I attached all the logs that I could think of. I am using the application with https, I do not know to much about network security but think there is some sort proxy, because I did not enable https acces in tomcat (it is exposing port 8080). Openshift is using TLS edge termination to create an https connection (but I am not sure what exactly that means)

[apollo_network_log.txt](https://github.com/GMOD/Apollo/files/4402387/apollo_network_log.txt)
[apollo_console_log_errors_only.txt](https://github.com/GMOD/Apollo/files/4402388/apollo_console_log_errors_only.txt)
[apollocontainer-40.log](https://github.com/GMOD/Apollo/files/4402410/apollocontainer-40.log)

**Comment by nathandunn** [comment]
@Jorisvansteenbrugge  A couple of comments looking at your logs:

1 - from the network logs, it seems like port-forwarding done by openshift is going to need additional proxies to work over https.   It sounds like it is forwarding an insecure local 8080 to a secure 443.  That's fine, but it needs to proxy the websockets correctly as well. 
 I have some guides for this: https://genomearchitect.readthedocs.io/en/latest/Configure.html#nginx-proxy-from-version-1-4-on (apache is in there, as well). 

Also, we have AWS servers that work out of the box (if you don't need security):

https://genomearchitect.readthedocs.io/en/latest/Aws_setup.html

I have been doing it this way with docker and then using nginx or apache for forwarding and using certbot to provide the https layer.

It might be worth posting to the apollo group (maybe you have) to see if anyone else has had luck with openshift. 

2 - while this won't affect what you are seeing from above, just an FYI, from your container log, it is starting PostgreSQL 9.6 , but then not allowing connections.  Makes me think that maybe the container is not up to date?     When I start up with the latest I see this:

```
 docker run -it -p 8888:8080 gmod/apollo:latest      
 * Starting PostgreSQL 9.6 database server                               [ OK ] 
WEBAPOLLO_HOST_FLAG: 
CHADO_HOST_FLAG: 
Waiting for DB
/var/run/postgresql:5432 - accepting connections
Postgres is up, configuring database
psql: FATAL:  Peer authentication failed for user "apollo"
Apollo database not found, creating...
CREATE ROLE
GRANT
Not using chado!
CATALINA_HOME '/usr/share/tomcat9'
CATALINA_BASE '/var/lib/tomcat9'
APOLLO PATH ''
...
```

When I create organisms, etc., I can confirm they are in there.
