### ISSUE TITLE
(2h) Organism panel not updating when organism is created or deleted

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#301]
I have observed that the organism panel does not update the organism list when you create (or delete) a new organism. Reason for this is unclear currently but I think it's probably just a small change on the backend that needs to be adapted to.

**Comment by nathandunn** [comment]
@cmdcolin   In OrganismController::saveOrganism()      sequenceService.loadRefSeqs() can potentially take a long time, which is what you're experiencing with Honeybee.  

    try {
            organism.save(failOnError: true, flush: true, insert: true)
            sequenceService.loadRefSeqs(organism)   //   <<<<<<<<<<
        } catch (e) {
            log.error("problem saving organism: " + e)
        }

A couple of solutions:
1 - freeze the screen during calculation . . . while in "create" create a glasspane
2 - move the "loadRefSeqs" into another Request call after the initial callback comes back, i.e., a nested callback.  

2) is probably preferable.  Shouldn't be too bad, just wiring.

**Comment by cmdcolin** [comment]
I know it used to take a long time but now it is just failing to update.

**Comment by nathandunn** [comment]
@cmdcolin   Good catch.  I centralized the data model into MainPanel instead of having multiple copies everywhere.    It should be working now. 

Not sure why functions like "delete" or so slow, but it might be due to the fact that it has to cascade deletions of Sequence.

**Comment by cmdcolin** [comment]
Looks good now! Big thanks

**Comment by cmdcolin** [comment]
I think it still doesn't update on the "first" time that you initialize an organism - connected trello card https://trello.com/c/qPma9VXk/440-when-creating-a-organism-for-first-time-it-doesn-t-load-it-into-the-genome-browser

**Comment by nathandunn** [comment]
It adds correctly, but its not resetting the address properly.  Also, it doesn't calculate the ref seq until later.  So this is what it looks like for yeast
![screen shot 2015-04-23 at 8 57 11 am](https://cloud.githubusercontent.com/assets/751274/7301311/d734757c-e996-11e4-88ab-6ebe828c0563.png)
:

**Comment by nathandunn** [comment]
So, it should either:
1 - not return until the ref seqeunces return
2 - send out an additonal request for ref sequences and update after then

For sure, *unless selected*, it should have a blank "Details" screen.  You can set the selection model or just have it be blank (better).

**Comment by cmdcolin** [comment]
This is the error the first time you create an organism

    Uncaught TypeError: Cannot read property 'clear_43_g$' of undefined
    onResponseReceived_7_g$ @ OrganismPanel.java:228
    fireOnResponseReceived_0_g$ @ Request.java:250
    onReadyStateChange_0_g$ @ RequestBuilder.java:412
    (anonymous function) @ XMLHttpRequest.java:329
    apply_0_g$ @ Impl.java:247entry0_0_g$ @ Impl.java:306
    (anonymous function) @ Impl.java:72

I can fix that pretty easily i think

**Comment by nathandunn** [comment]
This patch should fix it.

**Comment by cmdcolin** [comment]
Thanks, I am still getting this error though

    Uncaught com.google.gwt.event.shared.UmbrellaException: 2 exceptions caught:
    (TypeError) : Cannot read property 'getName_60_g$' of undefined;
    (TypeError) : Cannot read property 'getId_12_g$' of undefined

    castFireEvent_0_g$ @ EventBus.java:69
    fireEvent_3_g$ @ SimpleEventBus.java:57
    onResponseReceived_7_g$ @ OrganismPanel.java:233
    fireOnResponseReceived_0_g$ @ Request.java:250
    onReadyStateChange_0_g$ @ RequestBuilder.java:412
    (anonymous function) @ XMLHttpRequest.java:329
    apply_0_g$ @ Impl.java:247entry0_0_g$ @ Impl.java:306
    (anonymous function) @ Impl.java:72

**Comment by nathandunn** [comment]
The line from ORganismPanel is here:

organismChangeEvent.setAction(OrganismChangeEvent.Action.LOADED_ORGANISMS);
Annotator.eventBus.fireEvent(organismChangeEvent);


So, look for where this event and/or action is handled, specifically OrganismChangeEvent.TYPE:

Annotator.eventBus.addHandler(OrganismChangeEvent.TYPE, new OrganismChangeEventHandler() {

I guess I would add alert’s / breakpoints / GWT.log’s in one of these and see where its failing.

Nathan

**Comment by cmdcolin** [comment]
The two exceptions I added were fixed in https://github.com/GMOD/Apollo/commit/1f9772aef29ba553b963ca0219b3b61c7bfc803e and https://github.com/GMOD/Apollo/commit/1b4ed3f6bc94797bf4b0ca92d3d1ab8219f32d13

We still need to figure out how to load the refseqs though because that makes it so that the organism can't be selected even though it can be added

**Comment by nathandunn** [comment]
Hmm . . not entirely sure I follow, but this is my take:

Adding organism
- add organism 
- in callback call OrganismRestService::switchOrganism for the new organism (but create your own callback) . . . this refreshes the appstate appropriately

==== 
- delete organism is just the same, you just need to pick another organismID from the MainPanel.getInstance().organismInfoList

== 

So I think its close, just don't use the UpdateInfoListCallback(true) as teh callback for handleSaveNewOrganism and "DeleteButton". . .  just use a custom one (with anonymous classes) in each case.

**Comment by nathandunn** [comment]
Though you're callback should mirror what is going on in UpdateInfoListCallback in theory, but maybe just calling the "updatedAppState" might solve that problem anyway.     For something like the GlassPanel . . . adding a GWT Dialog while its loading and/or a glass panel should help . . . here is an example, though a lot of the incubator code is already in mainline:

https://code.google.com/p/google-web-toolkit-incubator/wiki/GlassPanel

**Comment by nathandunn** [comment]
Related to #330

**Comment by cmdcolin** [comment]
I went ahead and fixed this one too. It has a loading dialog similar to the mainpanel now and it correctly handled the button states a bit better.

**Comment by cmdcolin** [comment]
I'll mark this as review as i wasn't necessarily assigned

**Comment by nathandunn** [comment]
Cool . . MUCH better.

**Comment by monicacecilia** [comment]
brilliant. Thanks @cmdcolin and @nathandunn 
:dancer:
